### ISSUE TITLE
a student research energy consumption

### ISSUE THREAD

**Issue by kuangdongwei** [adelnoureddine/jolinar#1]
hey man, why can not I run this program,
I need more infomation about this ,thank you very very much

**Comment by adelnoureddine** [comment]
You can either install it using the rpm/deb packages, run it using the jar file, or compile it yourself following the readme documentation.

Note that to configure the tool, you need hardware information provided by constructors, in particular the voltages associated to the frequencies of your processor.
Some can be available from [CPUfreq stats](https://www.kernel.org/doc/Documentation/cpu-freq/cpufreq-stats.txt).

However, modern CPUs use the intel_pstate module which doesn't include cpufreq-stats. You need to disable it as in [this guide](https://askubuntu.com/questions/575730/cpufreq-stats-missing).

Also note, Jolinar 2.x hasn't been updated for a few years and is not supported anymore. More advanced tools and platforms can provide better energy consumption estimations, such as [PowerAPI](http://powerapi.org/).
